-- MySQL Script generated by MySQL Workbench
-- Wed May 11 11:48:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reserva Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_sobrenome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `email` VARCHAR(110) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dados do passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dados do passageiro` (
  `iddados` INT NOT NULL AUTO_INCREMENT,
  `tipo_de_pessoa` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `data_de_nasc` DATE NOT NULL,
  `nacionalidade` VARCHAR(30) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`iddados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passagens aéreas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passagens aéreas` (
  `idPassagens` INT NOT NULL AUTO_INCREMENT,
  `local_de_partida` VARCHAR(45) NOT NULL,
  `local_de_ida` VARCHAR(45) NOT NULL,
  `dia_de_ida` DATE NOT NULL,
  `dia_de_volta` DATE NOT NULL,
  `passageiros` INT(30) NOT NULL,
  PRIMARY KEY (`idPassagens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(110) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(8) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `sigla_UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`idEndereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `email` VARCHAR(110) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `login` VARCHAR(110) NOT NULL,
  `senha` VARCHAR(110) NOT NULL,
  `confirmação_senha` VARCHAR(110) NOT NULL,
  `Reserva Hotel_id` INT NOT NULL,
  `dados do passageiro_iddados` INT NOT NULL,
  `Passagens aéreas_idPassagens` INT NOT NULL,
  `Endereço_idEndereço` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Reserva Hotel1_idx` (`Reserva Hotel_id` ASC) VISIBLE,
  INDEX `fk_Cliente_dados do passageiro1_idx` (`dados do passageiro_iddados` ASC) VISIBLE,
  INDEX `fk_Cliente_Passagens aéreas1_idx` (`Passagens aéreas_idPassagens` ASC) VISIBLE,
  INDEX `fk_Cliente_Endereço1_idx` (`Endereço_idEndereço` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Reserva Hotel1`
    FOREIGN KEY (`Reserva Hotel_id`)
    REFERENCES `mydb`.`Reserva Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_dados do passageiro1`
    FOREIGN KEY (`dados do passageiro_iddados`)
    REFERENCES `mydb`.`dados do passageiro` (`iddados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Passagens aéreas1`
    FOREIGN KEY (`Passagens aéreas_idPassagens`)
    REFERENCES `mydb`.`Passagens aéreas` (`idPassagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Endereço1`
    FOREIGN KEY (`Endereço_idEndereço`)
    REFERENCES `mydb`.`Endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
