-- MySQL Script generated by MySQL Workbench
-- Wed May 11 11:48:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reserva_Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva_Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `reserva` VARCHAR(15) NOT NULL,
  `quarto` VARCHAR(15) NOT NULL,
  `data_chekin` DATE NOT NULL,
  `data_checkout` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dados_Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dados_Passageiro` (
  `iddados` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`iddados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passagens_Aereas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passagens_Aereas` (
  `idPassagens` INT NOT NULL AUTO_INCREMENT,
  `passageiros` VARCHAR(15) NOT NULL,
  `poltrona` VARCHAR(15) NOT NULL,
  `classe` VARCHAR(15) NOT NULL,
  `reserva` VARCHAR(15) NOT NULL,
  `origem` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `data_partida` DATE NOT NULL,
  `data_retorno` DATE NOT NULL,
  PRIMARY KEY (`idPassagens`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(110) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `usuario` VARCHAR(110) NOT NULL,
  `senha` VARCHAR(110) NOT NULL,
  `Reserva Hotel_id` INT NOT NULL,
  `dados do passageiro_iddados` INT NOT NULL,
  `Passagens aéreas_idPassagens` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Reserva Hotel1_idx` (`Reserva Hotel_id` ASC) VISIBLE,
  INDEX `fk_Cliente_dados do passageiro1_idx` (`dados do passageiro_iddados` ASC) VISIBLE,
  INDEX `fk_Cliente_Passagens aéreas1_idx` (`Passagens aéreas_idPassagens` ASC) VISIBLE,
  INDEX `fk_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Reserva Hotel1`
    FOREIGN KEY (`Reserva Hotel_id`)
    REFERENCES `mydb`.`Reserva Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_dados do passageiro1`
    FOREIGN KEY (`dados do passageiro_iddados`)
    REFERENCES `mydb`.`dados do passageiro` (`iddados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Passagens aéreas1`
    FOREIGN KEY (`Passagens aéreas_idPassagens`)
    REFERENCES `mydb`.`Passagens aéreas` (`idPassagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/* INSERIR */
INSERT INTO Cliente(nome_completo,data_nascimento,email,telefone,documento,usuario,senha) VALUES(?,?,?,?,?,?,?);
INSERT INTO Dados_Passageiro(nome_completo,sexo,data_nascimento,documento,telefone) VALUES(?,?,?,?,?);
INSERT INTO Passagens_Aereas(passageiros,poltrona,classe,reserva,origem,destino,data_partida,data_retorno) VALUES(?,?,?,?,?,?,?,?);
INSERT INTO Reserva_Hotel(nome_completo,data_nascimento,sexo,telefone,documento,reserva,quarto,dataCheckin,dataCheckout) VALUES(?,?,?,?,?,?,?,?,?);

/* CONSULTA */
SELECT * FROM Cliente;
SELECT * FROM Passagens_Aereas;
SELECT * FROM Dados_Passageiros;
SELECT * FROM Reserva_Hotel;
SELECT * FROM Cliente,Passagens_Aereas,Dados_Passageiro,Reserva_Hotel;

/* ATUALIZAR */
UPDATE Cliente SET nome_completo='??????';
UPDATE Passagens_Aereas SET destino='?????';
UPDATE Dados_Passageiro SET documento='??????';
UPDATE Reserva_Hotel SET data_checkin='?????';

/* DELETAR */
DELETE FROM Cliente WHERE nome_completo='??????';
DELETE FROM Passagens_Aereas WHERE idPassagens='?????';
DELETE FROM Dados_Passageiro WHERE nome_completo='?????';
DELETE FROM Reserva_Hotel WHERE documento='?????';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
