-- MySQL Script generated by MySQL Workbench
-- Wed May 11 11:48:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reserva_Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserva_Hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `reserva` VARCHAR(15) NOT NULL,
  `quarto` VARCHAR(15) NOT NULL,
  `data_checkin` DATE NOT NULL,
  `data_checkout` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dados_Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dados_Passageiro` (
  `iddados` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `Reserva_Hotel_id` INT(15),
  `Passagens_aereas_idPassagens` INT(15),
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`iddados`),
  INDEX `fk_Dados_Passageiro_Reserva_Hotel1_idx` (`Reserva_Hotel_id` ASC) VISIBLE,
  INDEX `fk_Dados_Passageiro_Passagens_aereas1_idx` (`Passagens_aereas_idPassagens` ASC) VISIBLE,
  INDEX `fk_Dados_Passageiro_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Dados_Passageiro_Reserva_Hotel1`
    FOREIGN KEY (`Reserva_Hotel_id`)
    REFERENCES `mydb`.`Reserva_Hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dados_Passageiro_Passagens_aereas1`
    FOREIGN KEY (`Passagens_aereas_idPassagens`)
    REFERENCES `mydb`.`Passagens_aereas` (`idPassagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dados_Passageiro_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passagens_Aereas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Passagens_Aereas` (
  `idPassagens` INT NOT NULL AUTO_INCREMENT,
  `passageiros` VARCHAR(15) NOT NULL,
  `poltrona` VARCHAR(15) NOT NULL,
  `classe` VARCHAR(15) NOT NULL,
  `reserva` VARCHAR(15) NOT NULL,
  `origem` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  `data_partida` DATE NOT NULL,
  `data_retorno` DATE NOT NULL,
  PRIMARY KEY (`idPassagens`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(110) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `documento` VARCHAR(15) NOT NULL,
  `usuario` VARCHAR(110) NOT NULL,
  `senha` VARCHAR(110) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Voo`(
`id` INT(15) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`localV` VARCHAR(50),
`disponibilidade` INT(10) NOT NULL DEFAULT '0'
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotel`(
`id` INT(15) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`localH` VARCHAR(50),
`disponibilidade` INT(10) NOT NULL DEFAULT '0'
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque`(
`id` INT(15) NOT NULL PRIMARY KEY AUTO_INCREMENT,
`Voo_id` INT(15) NOT NULL,
`Hotel_id` INT(15) NOT NULL,
`disponibilidade`INT(10) NOT NULL DEFAULT '0'
)
ENGINE = InnoDB;

/* INSERIR */
INSERT INTO Cliente(nome_completo,data_nascimento,email,telefone,documento,usuario,senha) VALUES('Vinicius Araujo de Oliveira','2001-05-14','viniaraujo@gmail.com','11900000000','00000000000','viniaraujo','pizza123');
INSERT INTO Dados_Passageiro(nome_completo,sexo,data_nascimento,documento,telefone,Reserva_Hotel_id,Passagens_aereas_idPassagens,Cliente_idCliente) VALUES('Vinicius Araujo de Oliveira','Masculino','2001-05-14','11900000000','00000000000','1','2','3');
INSERT INTO Passagens_Aereas(passageiros,poltrona,classe,reserva,origem,destino,data_partida,data_retorno) VALUES('1','42PC','Primeira Classe','1','São Paulo - Brasil','Nova York - EUA','2022-07-17','2002-07-27');
INSERT INTO Reserva_Hotel(nome_completo,data_nascimento,sexo,telefone,documento,reserva,quarto,data_checkin,data_checkout) VALUES('Vinicius Araujo de Oliveira','2001-05-14','Masculino','11900000000','00000000000','1','217B','2022-07-17','2022-07-27');

/* CONSULTA */
SELECT * FROM Cliente;
SELECT * FROM Passagens_Aereas;
SELECT * FROM Dados_Passageiro;
SELECT * FROM Reserva_Hotel;
SELECT * FROM Cliente,Passagens_Aereas,Dados_Passageiro,Reserva_Hotel;

/* ATUALIZAR */
UPDATE Cliente SET nome_completo='??????';
UPDATE Passagens_Aereas SET destino='?????';
UPDATE Dados_Passageiro SET documento='??????';
UPDATE Reserva_Hotel SET data_checkin='?????';

/* DELETAR */
DELETE FROM Cliente WHERE nome_completo='??????';
DELETE FROM Passagens_Aereas WHERE idPassagens='?????';
DELETE FROM Dados_Passageiro WHERE nome_completo='?????';
DELETE FROM Reserva_Hotel WHERE documento='?????';

/* DEFAULT - VALORES PADRÃO*/
ALTER TABLE Passagens_Aereas
MODIFY COLUMN destino VARCHAR(45) NOT NULL;

/* INDEX'S */
ALTER TABLE 
`Estoque`
ADD KEY `Cliente_idCliente`(`Clienet_idCliente`),
ADD KEY `Voo_id`(`Voo_id`),
ADD KEY `Hotel_id`(`Hotel_id`);

ALTER TABLE 
`Voo`
ADD KEY `localV`(`localV`);

ALTER TABLE 
`Hotel`
ADD KEY `localH`(`localH`);

ALTER TABLE 
`Cliente`
ADD UNIQUE KEY `nome_completo`(`nome_completo`);

ALTER TABLE 
`Estoque` ADD CONSTRAINT `Estoque_Voo_id_foreign` FOREIGN KEY(`Voo_id`) REFERENCES `Voo`(`id`),
ADD CONSTRAINT `Estoque_Cliente_idCliente_foreign` FOREIGN KEY(`Cliente_idCliente`) REFERENCES `Cliente`(`idCliente`);

ALTER TABLE
`Estoque` ADD CONSTRAINT `Estoque_Hotel_id_foreign` FOREIGN KEY(`Hotel_id`) REFERENCES `Hotel`(`id`),
ADD CONSTRAINT `Estoque_Cliente_idCliente_foreign` FOREIGN KEY(`Cliente_idCliente`) REFERENCES `Cliente`(`idCliente`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
